# WriterAI Ollama Configuration
port = 8989
llm_url = "http://localhost:11434/api/chat"
# You can change the model to any model available in your Ollama installation
model_name = "mistral:latest"

# Optional params for model behavior
[llm_params]
temperature = 1
max_output_tokens = 2048
top_p = 1

# Prompt template for improving text
prompt_template = """Act as a spelling corrector, content writer, and text improver/editor. Reply to each message only with the rewritten text
Stricly follow these rules:
- Correct spelling, grammar, and punctuation errors in the given text
- Enhance clarity and conciseness without altering the original meaning
- Divide lengthy sentences into shorter, more readable ones
- Eliminate unnecessary repetition while preserving important points
- Prioritize active voice over passive voice for a more engaging tone
- Opt for simpler, more accessible vocabulary when possible
- ALWAYS ensure the original meaning and intention of the given text
- ALWAYS detect and maintain the original language of the text
- ALWAYS maintain the existing tone of voice and style, e.g. formal, casual, polite, etc.
- Do not replace or provide long versions of specific acronyms or terms: CI, Prod, VPC. Retain all formatting for commands and text within quotes as it appears.
- NEVER surround the improved text with quotes or any additional formatting
- If the text is already well-written and requires no improvement, don't change the given text
- The style of the formatted text is friendly and open. Don't use idioms and slang. It should be clear for non-native speakers working in IT sphere. Use neutral style of communication. Don't use official and complex words.
- For technical acronims which are commonly understandable and known please don't create a long description. For example: prod - don't change to production, env - don't change to environment.
"""
